api/urls.py
from django.conf.urls import url
from .views import UserLoginAPIView,PostListAPIView, PostDetailAPIView, PostDeleteAPIView, PostCreateAPIView, PostUpdateAPIView, CommentListView, CommentCreateAPIView, UserCreateAPIView


urlpatterns = [
	url(r'^$', PostListAPIView.as_view(), name="list"),
	url(r'^register/$', UserCreateAPIView.as_view(), name="register"),
	url(r'^login/$', UserLoginAPIView.as_view(), name="login"),
	url(r'^comments/$', CommentListView.as_view(), name="comment-list"),
	url(r'^comments/create/$', CommentCreateAPIView.as_view(), name="comment-create"),
	url(r'^create/$', PostCreateAPIView.as_view(), name="create"),
	url(r'^(?P<post_slug>[-\w]+)/detail/$', PostDetailAPIView.as_view(), name="detail"), 
	url(r'^(?P<post_slug>[-\w]+)/delete/$', PostDeleteAPIView.as_view(), name="delete"),
	url(r'^(?P<post_slug>[-\w]+)/update/$', PostUpdateAPIView.as_view(), name="update"),   
]

blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'^posts/', include('posts.urls', namespace='more')),
	url(r'^comments/', include('django_comments.urls')),
	url(r'^googly/', include('googly.urls', namespace='googly')),
	url(r'^accounts/', include('allauth.urls')),
	url(r'^gitty/', include('gitty.urls', namespace='gitty')),
	url(r'^twitty/', include('twitty.urls', namespace='twitty')),
	url(r'^insta/', include('insta.urls', namespace='insta')),
	url(r'^api/', include('api.urls', namespace='api')),
]

if settings.DEBUG:
	urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [  
    url(r'^list/$', views.post_list , name="list"),
    url(r'^detail/(?P<post_slug>[-\w]+)/$', views.post_detail , name="detail"),

    url(r'^create/$', views.post_create , name="create"),
    url(r'^update/(?P<post_slug>[-\w]+)/$', views.post_update , name="update"),
    url(r'^delete/(?P<post_slug>[-\w]+)/$', views.post_delete , name="delete"),
    url(r'^like_button/(?P<post_id>\d+)/$', views.like_button , name="like_button"),
    url(r'^signup/$', views.usersignup , name="usersignup"),
    url(r'^login/$', views.userlogin , name="userlogin"),
    url(r'^logout/$', views.userlogout , name="userlogout"),
]

posts/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.template.defaultfilters import slugify
from django.db.models.signals import pre_save
from django.contrib.auth.models import User 

class Post(models.Model):
	author = models.ForeignKey(User, default=1)
	title = models.CharField(max_length=120)
	slug = models.SlugField(unique=True)
	content = models.TextField()
	draft = models.BooleanField(default=False)
	publish = models.DateField()
	updated = models.DateTimeField(auto_now=True)
	timestamp = models.DateTimeField(auto_now_add=True)
	img = models.ImageField(null=True, blank=True, upload_to="post_images")

	def __str__(self):
		#return str(self.updated)
		return self.title

	def get_abs_url(self):
		return reverse('more:detail', kwargs={"post_slug":self.slug})

	class Meta:
		ordering = ['title']


def create_slug(instance, new_slug=None):
	slug_value = slugify(instance.title)
	if new_slug is not None:
		slug_value = new_slug

	query = Post.objects.filter(slug=slug_value)
	if query.exists():
		slug_value = "%s-%s"%(slug_value, query.last().id)
		return create_slug(instance, new_slug=slug_value)
	return slug_value


def pre_save_post_function(*args, **kwargs):
	instance = kwargs['instance']
	if instance.slug: #to change the slug value each time the we update the instance title instance.slug=new/updated title of instance
		x = slugify(instance.title)
		instance.slug = create_slug(instance, new_slug=x)
	if not instance.slug:
		instance.slug = create_slug(instance)

pre_save.connect(pre_save_post_function, sender=Post)

class Like(models.Model):
	user = models.ForeignKey(User)
	post = models.ForeignKey(Post)
	created = models.DateTimeField(auto_now_add=True)
	

posts/forms.py
from .models import Post
from django import forms
from django.contrib.auth.models import User


class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = ['title', 'content', 'img' , 'draft' , 'publish']

		widgets={
		'publish': forms.DateInput(attrs={"type":"date"}),
		}


class UserSignup(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email' , 'password']

        widgets={
		'password': forms.PasswordInput(),
		}


class UserLogin(forms.Form):
	username = forms.CharField(required=True)
	password = forms.CharField(required=True, widget=forms.PasswordInput())
	    

posts/views.py
from django.shortcuts import render, redirect
from .models import Post
from .forms import PostForm, UserLogin, UserSignup
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from urllib.parse import quote
from django.http import Http404, JsonResponse
from django.utils import timezone
from django.db.models import Q
from .models import Like
from django.contrib.auth import authenticate, login, logout


def usersignup(request):
	context = {}
	form = UserSignup()
	context['form'] = form
	if request.method == 'POST':
		form = UserSignup(request.POST)
		if form.is_valid():
			user = form.save()

			# to change the value of password since it should encrupte 
			username = user.username
			password  = user.password

			user.set_password(password) # to hash the  password
			user.save()

			#after saving user we want to log in the same user
			#Check if user authenticted to log in or not 
			auth = authenticate(username=username, password=password) # first username is a Field in User Model and same for password
			login(request, auth)


			return redirect("more:list")
		messages.warning(request, form.errors)
		return redirect("more:usersignup")
	return render(request, 'signup.html', context)




def userlogin(request):
	context = {}
	form = UserLogin()
	context['form'] = form
	if request.method == 'POST':
		form = UserLogin(request.POST)
		if form.is_valid():
			some_username = form.cleaned_data['username']
			some_password = form.cleaned_data['password']

			auth = authenticate(username=some_username, password=some_password)
			if auth is not None:
				login(request, auth)
				return redirect("more:list")
			messages.warning(request, "Incorrect username / password combination.")
			return redirect("more:userlogin")
		messages.warning(request, form.errors)
		return redirect("more:userlogin")
	return render(request, 'login.html', context)



def userlogout(request):
	logout(request)
	return redirect("more:list")




def post_list(request):
	today = timezone.now().date()	
	objects = Post.objects.filter(draft=False, publish__lte=today)
	#objects = Post.objects.all().oredr_by('title', 'id')

	if request.user.is_staff:
		objects = Post.objects.all()

	query = request.GET.get('q')
	if query:
		objects = Post.objects.filter(
			Q(title__icontains=query)|
			Q(content__icontains=query)|
			Q(author__first_name__icontains=query)|
			Q(author__last_name__icontains=query)
			).distinct()

	#paginations
	paginator = Paginator(objects, 4) # Show 25 contacts per page

	number = request.GET.get('page')

	try:
		objects = paginator.page(number)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		objects = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		objects = paginator.page(paginator.num_pages)

	context = {
		"post_items": objects,
		"today": today,
	}
	return render (request, "list.html", context)






def post_detail(request, post_slug):
	item = Post.objects.get(slug=post_slug)
	# item = Post.objects.get_object_or_404(Post, id=1000)

	if not request.user.is_staff:
		if item.draft or item.publish > timezone.now().date():
			raise Http404

	if request.user.is_authenticated():
		if Like.objects.filter(post= item, user=request.user).exists():
			like = True
		else:
			like = False

	like_count = item.like_set.count()

	context = {
		"item": item,
		"liked": like,
		"like_count": like_count,
		"share_string": quote(item.content),
	}
	return render (request, "detail.html", context)




def post_create(request):
	if not (request.user.is_staff or request.user.is_superuser): # if not request.user.is_authenticated(): return 'login'
		raise Http404
	form = PostForm(request.POST or None, request.FILES or None )
	if form.is_valid():
		item = form.save(commit=False)
		item.author = request.user
		item.save()
		messages.success(request, "Added Successfully :)")
		return redirect("more:list")
	context = {
		'form': form
	}
	return render (request, "post_create.html", context)






def post_update(request, post_slug):
	if not (request.user.is_staff or request.user.is_superuser):
		raise Http404
	item = Post.objects.get(slug=post_slug)
	form = PostForm(request.POST or None,request.FILES or None ,instance = item)

	if form.is_valid():
		form.save()
		messages.info(request, "Updated Successfully :)")
		return redirect("more:list")
	context = {
		'form': form,
		"item": item,
	}
	return render (request, "post_update.html", context)






def post_delete(request, post_slug):
	if not (request.user.is_staff or request.user.is_superuser):
		raise Http404
	item = Post.objects.get(slug=post_slug).delete()
	messages.warning(request, "Noooooooo :(")
	return redirect("more:list")



def like_button(request, post_id):
	post_object = Post.objects.get(id=post_id)
	like, created = Like.objects.get_or_create(user=request.user, post=post_object)

	if created:
		action="like"
	else:
		like.delete()
		action="unlike"

	like_count = post_object.like_set.count()
	response = {
		"action": action,
		"like_count": like_count,
	}
	return JsonResponse(response, safe=False)

posts/templates/base.html
<!DOCTYPE html>
{% load static %}
{% load crispy_forms_tags %}

<html lang="en">
<head>
	<meta charset="utf-8">
	<title>{% block heading%} {% endblock heading %}</title>
	<!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">-->

	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
	
	{% include "navbar.html" %}

	{% include "messages.html" %}


	<div class="container">
		{% block content%}

		{% endblock content%}
	</div>
	<!--<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>-->
	<div class="navbar navbar-expand-lg navbar-light bg-light" >		
		<p style="padding:5px;">&copy; Coded {% now 'Y' %}</p>
	</div>


	<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'js/popper.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
	<script type="text/javascript">
		$(function () {
		  $('[data-toggle="tooltip"]').tooltip()
		})
	</script>
</body>
</html>

posts/templates/comments.html
{% load crispy_forms_tags %}

{% load comments %}

{% get_comment_list for item as comments %}

{% for comment in comments %}
	<div class="alert alert-info" role="alert"><b>{{ comment.user_name }} said:</b> {{ comment.comment|linebreaks}}</div>
{% endfor %}

{% get_comment_form for item as form %}

{% if  not request.user.is_authenticated %}
	<h1>Please l=Log in To a comment</h1>
{% else %}
	<form action="{% comment_form_target %}" method="POST">
		{% csrf_token %}
		<input type="hidden" name="name" value="{{ request.user.username }}">
		<input type="hidden" name="email" value="{{ request.user.email }}">
		<input type="text" class="form-control input-lg" name="comment">
		{{ form.content_type }}
		{{ form.object_pk }}
		{{ form.timestamp }}
		{{ form.security_hash }}
		<input type="hidden" name="next" value="{{item.get_abs_url}}">
		<input type="submit" name="submit" class="btn btn-primary">
	</form>
{% endif %}

posts/templates/detail.html
{% extends "base.html" %}

{% load share%}

{% block heading %} Detail {% endblock heading%}

{% block content%}
	<div class="jumbotron">
		<h1 class="display-3">{{item.title}}</h1>
		<p class="lead">{{item.content}}</p>

		{% if item.img %}
			<img src="{{item.img.url}}" alt="card image" class="card-img-top" style="height: 30%; width: 30%;">
		{% endif %}

		<hr class="my-4">
		<p><small>{{item.updated|timesince}}</small></p>
	</div>

	<a class="btn btn-primary" href="https://www.facebook.com/sharer/sharer.php?u={{request.build_absolute_uri}}">
	<i class="fa fa-facebook" aria-hidden="true"></i>
	</a>

	<a class="btn btn-warning" href="https://twitter.com/home?status={{share_string}}%20{{request.build_absolute_uri}}">
	<i class="fa fa-twitter" aria-hidden="true"></i>
	</a>

	<a class="btn btn-success" href="https://www.linkedin.com/shareArticle?mini=true&url={{request.build_absolute_uri}}&title={{item.title|share}}&summary={{item.content|truncatechars:140|share}}&source={{request.build_absolute_uri}}">
	<i class="fa fa-linkedin" aria-hidden="true"></i>
	</a>

	<div class="btn btn-dark" style="float:right;" onclick="ajax_like()">
		<span id="likes_count">{{like_count}}</span>
		<span ><i id="heart" class="fa fa-heart {% if liked %}text-danger{% endif %} " aria-hidden="true"></i></span>
	</div>
	<br>
	<br>
	{% include "comments.html" %}

	<script>
		function ajax_like() {
			// body...
			$.ajax(
				{
					type: 'GET',
					url: '{% url "more:like_button" post_id=item.id %}',
					error:function () {
						console.log("Error");
					},
					success:function (data) {
						console.log(data)
						$("#likes_count").text(data.like_count);
						if (data.action==="like"){
							$("#heart").addClass("text-danger");
						}else{
							$("#heart").removeClass("text-danger"); 
						}
					},
				});			
		}
	</script>

{% endblock content%}

posts/templates/list.html
{% extends "base.html" %}
{% load static from staticfiles %}


{% block heading %} 
	List 
{% endblock heading%}

{% block content%}
	<style>
		
	</style>
	
	{% include 'messages.html' %}

	<div>
		<div class="jumbotron" style="margin-top:7%;">
			<h1 class="display-3">Blogs</h1>	  
			<p class="lead">
				<a class="btn btn-primary btn-lg" href="{% url 'more:create' %}" role="button">Create</a>
			</p>


			<form action="{% url 'more:list' %}" method="GET">
				<input type="text" name="q" placeholder="search ..." value="{{request.GET.q}}">
				<input type="submit" value="search">
			</form>
		</div>


		<div class="row">
			{% for c in post_items %}
				<div class="card col-sm-12 col-md-3" style="margin:10px;height:20%;width:30%;">
					<div class="card-body">
						<h4 class="card-title">{{c.title}} 
							<small>{{c.publish|timesince}}</small>
							{% if c.draft %}
								<span class="text-danger">Draft</span>
							{% endif %}

							{% if c.publish > today %}
								<span class="text-success">Future Post</span>
							{% endif %}
						</h4>

						{% if c.img %}
			    			<img src="{{c.img.url}}" alt="card image" class="card-img-top">
			    		{% else %}
			    			<img src="{% static "images/avatar.png" %}" alt="card image" class="card-img-top">
			    		{% endif %}

						<p class="card-text">{{c.content|linebreaks|truncatechars:50}}</p>
						<p class="card-text">{{c.author}}</p>
						<p class="card-text">{{c.author.get_full_name}}</p>
						<p class="card-text">{{c.author.last_login}}</p>
						<p class="card-text">{{c.author.date_joined}}</p>
						<p class="card-text">{{c.author.userename}}</p>
					</div>

					<ul class="list-group list-group-flush">
						<a href="{% url 'more:delete' post_slug=c.slug %}" class="list-group-item btn btn-warning" data-toggle="tooltip" data-placement="top" title="delete ">Delete <i class="fa fa-trash" aria-hidden="true"></i></a>
			    		<a href="{% url 'more:update' post_slug=c.slug %}" class="list-group-item btn btn-warning">Update <i class="fa fa-pencil" aria-hidden="true"></i></a>
			    		<a href="{% url 'more:detail' post_slug=c.slug %}" class="list-group-item btn btn-warning">Read More <i class="fa fa-book" aria-hidden="true"></i></a>
			    		<a href="{{c.get_abs_url}}" class="list-group-item btn btn-warning">Details <i class="fa fa-info" aria-hidden="true"></i></a>
					</ul>
				</div>
				{% empty %}
					<h1 class="text-danger">Sorry, no search results for {{request.GET.q}}</h1>
			{% endfor %}
		</div>



		<div class="pagination" style="margin-top:2%;">
		    <span class="step-links">
		        {% if post_items.has_previous %}
		            <a href="?page={{ post_items.previous_page_number }}&q={{request.GET.q}}">previous</a>
		        {% endif %}

		        <span class="current">
		            Page {{ post_items.number }} of {{ post_items.paginator.num_pages }}.
		        </span>

		        {% if post_items.has_next %}
		            <a href="?page={{ post_items.next_page_number }}&q={{request.GET.q}}">next</a>
		        {% endif %}
		    </span>
		</div>

	</div>
{% endblock content%}

posts/templates/loanCalculator.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Loan Calculator</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
	<form method="POST">
		<div class="dropdown">
			<button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			    Finance & Product types
			</button>
			<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
				<div class="dropdown-item" >Consumer finance</div>
				<div class="dropdown-item" >Installment finance</div>
				<div class="dropdown-item" >Auto finance</div>
			</div>
		</div>
		Customer Name: <input type="text" name="fname"><br>
		<div class="form-group">
			<label for="exampleFormControlInput1">Email address</label>
			<input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
		</div>
		Mobile Number: <input type="text" name="fname"><br>
		<div class="dropdown">
			<button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			    Purpose of Finance
			</button>
			<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
				<div class="dropdown-item" >Construction material</div>
				<div class="dropdown-item" >car</div>
				<div class="dropdown-item" >medical treatment</div>
				<div class="dropdown-item" >education services</div>
				<div class="dropdown-item" >consumer goods</div>
			</div>
		</div>
		Monthly Salary: <input type="text" name="fname"><br>
		Down Payment: <input type="text" name="fname"><br>
		Finance Amount: <input type="text" name="fname"><br>
		Finance Tenor: <input type="text" name="fname"><br>

		<button type="submit" class="btn btn-primary">Submit</button>

	</form>


















	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
	<script type="text/javascript">
		$(function () {
		  $('[data-toggle="tooltip"]').tooltip()
		})
	</script>
</body>
</html>

posts/templates/login.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block heading %} Log in {% endblock heading%}

{% block content%}
	<br><br><br>
	<form action="{% url 'more:userlogin' %}" method="POST" enctype="multipart/form-data">
		{% csrf_token %}
	   {# {{form.as_p}} #}
	   {{form|crispy}}
	   <input type="submit" value="Log in" class="btn btn-success">
	   <a href="{% url 'github_login' %}" class="btn btn-dark"><i class="fa fa-github-alt" aria-hidden="true" ></i> Login Using GitHub</a>
	   <a href="{% url 'twitter_login' %}" class="btn btn-info"><i class="fa fa-twitter" aria-hidden="true" ></i> Login Using Twitter</a>
	   <a href="{% url 'instagram_login' %}" class="btn btn-primary"><i class="fa fa-instagram" aria-hidden="true" ></i> Login Using Instagram</a>
   </form>
   
{% endblock content%}

posts/templates/messages.html
{% if messages %}
	<div class="messages">
		{% for message in messages %}
		<div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
		{% endfor %}
	</div>
{% endif %}

posts/templates/navbar.html
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light" style="background-color: #e3f2fd;margin-bottom:10px;">
	<a class="navbar-brand" href="{% url 'more:list' %}">Blog</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	<span class="navbar-toggler-icon"></span>
	</button>

	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav mr-auto">
			<li class="nav-item active"> <a class="nav-link" href="{% url 'more:list' %}">Home <span class="sr-only">(current)</span></a></li>
					{# <li class="nav-item"><a class="nav-link" href="#">Link</a></li> #}
			{% if request.user.is_staff %}				
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Other</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
						<a class="dropdown-item" href="{% url 'more:create' %}">Create Post</a>
					<div class="dropdown-divider"></div>
									<!--<a class="dropdown-item" href="#">Something else here</a>-->
					</div>
				</li>
			{% endif %}

			{% if request.user.is_authenticated %}
				<li class="nav-item">
					<a class="nav-link" href="{% url 'more:userlogout' %}">Log out</a>
				</li> 
				<li class="nav-item">
					<a class="nav-link disabled" href="#">{{request.user}}</a>
				</li> 
			{% else %}
				<li class="nav-item">
					<a class="nav-link" href="{% url 'more:usersignup' %}">Sign up</a>
				</li> 
				<li class="nav-item">
					<a class="nav-link" href="{% url 'more:userlogin' %}">Log in</a>
				</li> 
			{% endif %}	

			
		</ul>
		<form class="form-inline my-2 my-lg-0" action="{% url 'more:list' %}" method="GET">
			<input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
			<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
		</form>
	</div>
</nav>

posts/templates/post_create.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block heading %} Create {% endblock heading%}

{% block content%}
	<form action="{% url 'more:create' %}" method="POST" enctype="multipart/form-data">
		{% csrf_token %}
	   {# {{form.as_p}} #}
	   {{form|crispy}}
	   <input type="submit" value="create">
   </form>
{% endblock content%}

posts/templates/post_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block heading %} Update {% endblock heading%}

{% block content%}
<br><br><br>
	<form action="{% url 'more:update' post_slug=item.slug %}" method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		{{form|crispy}}
		<input type="submit" value="update">
   </form>
{% endblock content%}

posts/templates/signup.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block heading %} Sign Up {% endblock heading%}

{% block content%}
<br><br><br><br>
	<form action="{% url 'more:usersignup' %}" method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		{# {{form.as_p}} #}
		{{form|crispy}}
		<input type="submit" value="sign up" class="btn btn-dark">
		<a href="{% url 'github_login' %}" class="btn btn-dark"><i class="fa fa-github-alt" aria-hidden="true" ></i> Login Using GitHub</a>
	</form>
{% endblock content%}