api/urls.py
from django.conf.urls import url
from .views import UserLoginAPIView,PostListAPIView, PostDetailAPIView, PostDeleteAPIView, PostCreateAPIView, PostUpdateAPIView, CommentListView, CommentCreateAPIView, UserCreateAPIView


urlpatterns = [
	url(r'^$', PostListAPIView.as_view(), name="list"),
	url(r'^register/$', UserCreateAPIView.as_view(), name="register"),
	url(r'^login/$', UserLoginAPIView.as_view(), name="login"),
	url(r'^comments/$', CommentListView.as_view(), name="comment-list"),
	url(r'^comments/create/$', CommentCreateAPIView.as_view(), name="comment-create"),
	url(r'^create/$', PostCreateAPIView.as_view(), name="create"),
	url(r'^(?P<post_slug>[-\w]+)/detail/$', PostDetailAPIView.as_view(), name="detail"), 
	url(r'^(?P<post_slug>[-\w]+)/delete/$', PostDeleteAPIView.as_view(), name="delete"),
	url(r'^(?P<post_slug>[-\w]+)/update/$', PostUpdateAPIView.as_view(), name="update"),   
]

blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'^posts/', include('posts.urls', namespace='more')),
	url(r'^comments/', include('django_comments.urls')),
	url(r'^googly/', include('googly.urls', namespace='googly')),
	url(r'^accounts/', include('allauth.urls')),
	url(r'^gitty/', include('gitty.urls', namespace='gitty')),
	url(r'^twitty/', include('twitty.urls', namespace='twitty')),
	url(r'^insta/', include('insta.urls', namespace='insta')),
	url(r'^api/', include('api.urls', namespace='api')),
]

if settings.DEBUG:
	urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

googly/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [  
	url(r'^place/search/$', views.place_text_search , name="place-search"),
	url(r'^place/detail/$', views.place_detail , name="place-detail"),
]

googly/views.py
from django.http import JsonResponse
from django.shortcuts import render
import requests

def place_text_search(request):
	key = "AIzaSyDdxE9l_bwR6oE16yGPLPZWnrHaUh4lXjc" #authenticate to access google api
	#query = "bank"
	query=request.GET.get('query', 'bank') #query is the thing that what you want to search about  # first arg is the html input element name , second is the default value if there is no data in query 
	url = "https://maps.googleapis.com/maps/api/place/textsearch/json?query=%s&region=kw&key=%s"%(query, key)

	next_page = request.GET.get('nextpage')
	if next_page is not None:
		url += "&pagetoken=" + next_page # add the string to the end of url

	response = requests.get(url)

	context = {
		"response" : response.json(),
	}
	#return JsonResponse(response.json(), safe=False)
	return render(request, "place_search.html", context)


def place_detail(request):
	key = "AIzaSyDdxE9l_bwR6oE16yGPLPZWnrHaUh4lXjc"
	place_id = request.GET.get('place_id', '')
	url = "https://maps.googleapis.com/maps/api/place/details/json?key=%s&placeid=%s"%(key,place_id)

	response = requests.get(url)
	map_key = "AIzaSyD9pGoidGfHSyxhN_CcyRyHVWqVBoTbY14"

	context = {
		"response" : response.json(),
		"map_key": map_key,
	}

	#return JsonResponse(response.json(), safe=False)
	return render(request, "place_detail.html", context)

googly/templates/place_detail.html
{% extends "base.html" %}

{% block heading %} Detail {% endblock heading%}

{% block content%}

<div class="card" style="margin:10%;">
  <div class="card-header">{{response.result.vicinity}}</div>
  <div class="card-body">
    <h4 class="card-title">{{response.result.name}}</h4>
    <p class="card-text">Address : {{response.result.formatted_address}}</p>
    <a href="{{response.result.url}}" class="btn btn-danger"><i class="fa fa-map-marker" aria-hidden="true"></i></a>
  </div>
</div>


<iframe
  id="map"
  width="600"
  height="450"
  frameborder="0" style="border:0"
  src="" allowfullscreen>
</iframe>

<script>

	function do_something(lat, lng) {
		var map = $("#map");
		map.attr(
			'src',
			"https://www.google.com/maps/embed/v1/directions?key={{map_key}}&origin="+lat+","+lng+"&destination={{response.result.geometry.location.lat}},{{response.result.geometry.location.lng}}"
			)
	}

	navigator.geolocation.getCurrentPosition(function(position) {
  	do_something(position.coords.latitude, position.coords.longitude);
	});

</script>
{% endblock content%}

googly/templates/place_search.html
{% extends "base.html" %}

{% block heading %} Google Results {% endblock heading%}

{% block content%}

<div style="margin:5%;">
	<form action="{% url 'googly:place-search' %}" method="GET">
		<div class="col-lg-6">
			<div class="input-group">
			  	<input type="text" class="form-control" placeholder="Search for..." aria-label="Search for..." name="query">
			  	<span class="input-group-btn">
				<button class="btn btn-secondary" type="submit">Search</button>
			  	</span>
			</div>
		</div>
	</form>
</div>
	<table class="table" >
		<thead>
			<tr>
				<th scope="col">Name</th>
				<th scope="col">Address</th>
				<th scope="col">Detail</th>
			</tr>
		</thead>
		<tbody>
			{% for place in response.results %}
			<tr>
				<td>{{place.name}}</td>
				<td>{{place.formatted_address}}</td>
				<td>
					<form action="{% url 'googly:place-detail' %}">
						<input type="hidden" name="place_id" value="{{place.place_id}}">
						<input type="submit" value="Detail" class="btn btn-outline-info">
					</form>
				</td>
			</tr>
			{% endfor %}		
		</tbody>		
	</table>


		{# if I recieve a next_page_token string and it is have av value not None #}
			{% if response.next_page_token %}  
				<form action="{% url 'googly:place-search' %}" method="GET">
					<input type="hidden" name="nextpage" value="{{response.next_page_token}}">
					<input type="submit" value="more results ... " class="btn btn-outline-info">
				</form>
			{% endif %}	

{% endblock content%}